thermondo/django-heroku-connect

- requirements.txt
- tox.ini
readthedocs.io needs Django in the requirements file.
> Add Django to requirements

- heroku_connect/db/models/base.py
- heroku_connect/utils.py
- tests/db/models/test_base.py
Make sure `managed=False` is always added to the Heroku Connect models
since the migration state will only pick up explicitly created Meta
attributes.
> Fix migration options

- heroku_connect/db/models/fields.py
- tests/db/models/test_fields.py
* In some cases an ID field is there but it's not unique since it's a reference to some other object.
* about the nullable flag, whenever you create a new object that needs to be synced to salesforce, initially ID(`sf_id`) is `null`, then when heroku connect syncs it, it fills it out...
> Make id field nullable or unique by kwargs

- heroku_connect/db/models/fields.py
- tests/db/models/test_fields.py
Picklists seem to be mapped to at least varchar(255) even if the
choices are shorter.
> Fix Picklist max_length

- heroku_connect/db/models/base.py
- tests/db/models/test_base.py
Django migrations do not call the models meta calls but only use
the options defined in the migration. Should someone add constraints
to a heroku connect model, this will fail because the migration
state of the Heroku Connect model does not reflect the actual
table name.
> Fix migrations -- Add missing table name

- tests/testapp/settings.py
Read the docs still uses Python 3.5. Secrests was only introduced
in Python 3.6
> Drop secrets dependency in docs

- heroku_connect/utils.py
The payload should be in the `params` not `data` keyword attribute.
Before `get_connections` would return connections for all apps and
not only the given one.
> Fix missing payload issue

- heroku_connect/db/backends/base/creation.py
- heroku_connect/utils.py
Django's pre_migrate singal is called once of each app. The signal
receiver needs to handle this fact and only act if it was called
for the Heroku Connect app.
> Run create schema command only when test db is created

- setup.cfg
Git isn't tracking these files, so if `openstack-dev/pbr` autocreates them, they end up as unstaged changes in the local working tree. This change tells `pbr` to stop this madness.
> Don't autocreate AUTHORS and ChangeLog

- heroku_connect/apps.py
- heroku_connect/checks.py
- tests/test_checks.py
- tests/testapp/models.py
Foreign keys that use strings to reference the foreign object
have priouly been ignored.
> Fix foreign key check

- heroku_connect/management/commands/import_mappings.py
- tests/commands/test_import_mappings.py
Mappings are imported asynchronouly in Heroku Connect. The connection
state reflects the import event and will change back to idle or an
error state once the import is completed.
> Resolve #36 -- Add wait argument to import_mappings command

- .travis.yml
Using a different build stage stops the travis deploy command from running for every build in the build matrix. 
This could also be accomplished by using a condition on the deploy to limit it to one build; however, then the deployment would take place even if other builds fail. The deploy stage, on the other hand, waits for the previous testing stage to succeed.
Note:
* this travis feature is still in beta;
* I didn't test this;
* I *did* try https://lint.travis-ci.org/, but it's outdated and doesn't recognize the "jobs" key.
* Let's see what travis thinks about the `.travis.yml` in this PR. 
See also:
https://docs.travis-ci.com/user/build-stages/
https://docs.travis-ci.com/user/build-stages/matrix-expansion/
https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
> Don't run deploy for every travis build

- .gitignore
- docs/exceptions.rst
- docs/quick_start.rst
- docs/router.rst
- heroku_connect/db/exceptions.py
- heroku_connect/db/models/base.py
- heroku_connect/db/router.py
- tests/conftest.py
- tests/db/models/test_base.py
- tests/test_utils.py
- tests/testapp/models.py
- tests/testapp/settings.py
Raise `WriteNotSupportedError` if both model and QuerySet methods
are called that try to perform write actions on read-only mappings.
> Add database router to prevent write actions on read-only tables

- heroku_connect/db/models/base.py
* Allow null values for _hc_lastop
* Allow null values for _hc_err
> Fix ORM representation of built in Heroku Connect fields

- tests/commands/test_import_mappings.py
There's no need to have the test sleep for 10 seconds between mocked requests.
> Do not sleep in test_import_mappings

- README.rst
- docs/quick_start.rst
Hi,
While setting this up I encountered a problem, found out that we have a small bug in setup instructions.
Instructions refer to `heroku_connect.db.backends.postgres`, but the package has slightly different path:
https://github.com/Thermondo/django-heroku-connect/tree/master/heroku_connect/db/backends/postgresql
> Fix setup instructions

- heroku_connect/db/backends/base/creation.py
- heroku_connect/migrations/0001_initial.py
- heroku_connect/utils.py
- setup.cfg
- tests/test_utils.py
This fixes a ProgrammingError when running tests with `--reuse-db`, where `create_test_db` would attempt to create the trigger log tables even though they already exist.
> Auto-create trigger log tables only when necessary.

- docs/error_handling.rst
- heroku_connect/admin.py
- heroku_connect/models.py
- tests/conftest.py
- tests/test_admin.py
The trigger log `state` is no longer editable in the admin. Instead, there are list actions that allow retrying failed log actions:
* `TriggerLog` entries have their state set to `NEW`.
* `TriggerLogArchive` entries get copied into `NEW` trigger log rows and set to `REQUEUED`.
This is basically the recovery procedure from the [docs] for the merged write algorithm; it also works in a lot of cases for the ordered-writes algorithm. If it doesn't work, it's still possible to run `log.capture_insert` or `log.capture_update` in the console.
[docs]: https://devcenter.heroku.com/articles/writing-data-to-salesforce-with-heroku-connect#merged-writes-algorithm
It's also possible set FAILED logs to IGNORED, effectively silencing the errors in the web dashboard.
> Add admin actions to ignore and retry failed logs

- heroku_connect/conf.py
This setting was hardcoded, but we need it to be flexible.
> Allow `HEROKU_CONNECT_SCHEMA` to be set from the settings

- heroku_connect/utils.py
The anchor was broken, this PR fixes it.
> Fix heroku_connect.utils.link_connection_to_account docstring

- .travis.yml
- README.rst
- tox.ini
1. This PR **adds official Travis package, called `tox-travis`** (https://tox-travis.readthedocs.io/en/stable/) to simplify test suite.
Previously we defined complicated matrix in Travis config to run all possible version and service variations we have. Now this package handles all that, we only need to specify which python versions to run against. This looks much cleaner and simpler to maintain.
Linting tasks are running under python 3.6 environment since version does not really matter here (instead of having expensive separate job).
2. I **migrated** this repo **from travis-ci.org**, which is deprecated now, to **travis-ci.com**, which is now a single source for all repositories (public and private).
3. I **upgraded to PostgreSQL 10** in our CI, since 9.6 is being deprecated.
> Revisit CI config: add tox-travis

- docs/spelling_wordlist.txt
- heroku_connect/contrib/heroku_connect_health_check/__init__.py
- heroku_connect/db/models/base.py
- tests/db/models/test_base.py
- tests/test_utils.py
This reverts commit adfac9be2756115c091d0f28605871179aec3123.
as discussed in https://github.com/Thermondo/thermondo-backend/pull/13998 we actually don't need this any more, and the use-case for other users doesn't exist. 
Heroku Support explanation:
```
Thanks for reaching out.
>Am I safe to assume that Heroku Connect deletes the records in postgres that are trashed in Salesforce? Is the column used only temporarily?
You're correct - we need to clarify this in the documentation. We use the isDeleted field under the hood in sync operations, but as soon as a record is soft-deleted in Salesforce, we hard-delete it from Postgres. So deleted records will get removed from the Postgres table altogether.
>If yes, what's the time between the deleted record appearing and it being deleted?
It would …
```
> Revert "is_deleted field should have an index (#85)"

- heroku_connect/models.py
- heroku_connect/utils.py
- tests/conftest.py
- tests/test_admin.py
- tests/test_models.py
- for `OrderedWrites`, the [heroku docs](https://devcenter.heroku.com/articles/writing-data-to-salesforce-with-heroku-connect#ordered-writes-algorithm) state that retrying should be done through `hc_capture_insert_from_row` and `hc_capture_update_from_row`. 
- now we are doing this
- update passes
- update fails with validation rule
- retry of update fails again (but is creating a new trigger-log record)
- retry passes when validation rule is dropped / fixed
and the same for insert
> use recapture when doing `redo` on ordered-write errors

- heroku_connect/db/models/fields.py
> Add `TextAreaLong` to __all__ along with the other classes

- heroku_connect/admin.py
- heroku_connect/models.py
- tests/testapp/models.py
...with `gettext_lazy`
```
RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
```
> Replace deprecated Django ugettext_lazy

- .github/workflows/ci.yml
- tests/db/models/test_base.py
- tests/testapp/settings.py
- tox.ini
In 3.2 primary_keys behaviour changed a bit:
https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys
This is affecting our tests, need to dig deeper into it.
> Update CI test matrix: Add Django 3.2, drop Python 3.6, Django 3.0

- heroku_connect/models.py
- tests/test_models.py
[ScoutAPM](https://scoutapm.com) breaks when it tries to measure query performance on raw queries that use [psycopg2's SQL string composition](https://www.psycopg.org/docs/sql.html). This is a workaround to convert composed queries to strings before running the raw query.
Submitted issue with Scout here: https://github.com/scoutapp/scout_apm_python/issues/749
> Convert Composed query to str before running raw query

- .github/workflows/ci.yml
- .github/workflows/release.yml
- setup.cfg
We are getting a few GitHub Actions warnings, at least one of them potentially a security issue.
This should resolve _most_ of our current warnings. A little more work would be required to get everything all the way up-to-date, but this should be good enough for today.
> Update Actions to resolve warnings

- docs/conf.py
- heroku_connect/contrib/heroku_connect_health_check/backends.py
- heroku_connect/utils.py
- tests/contrib/test_healthcheck.py
- tests/fixtures.py
This is coming from a production problem where a mapping was broken because the related SF field was dropped in SF. 
In this case the sync for that object was completely stopped by Heroku, but we didn't get any notifications for this. 
With this change here we now also check the mapping states and raise errors accordingly, so we would see a down-alert in this case.
> extend healthcheck to fail when a single mapping is in a broken state

- .github/workflows/ci.yml
- heroku_connect/management/commands/import_mappings.py
- heroku_connect/test/utils.py
- pyproject.toml
- setup.cfg
- tests/commands/test_import_mappings.py
- tests/commands/test_load_remote_schema.py
also this drops us testing pg13 with django 5.1. I'm not sure why it fails, but I'm relatively certain it's not because of us
> add Django 5.2 support, drop discontinued 5.0
